version: '3'

services:
  postgres:
    image: postgres
    container_name: task-trek
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_trek_db
    ports:
      - '5432:5432'
